version: "2"
services:

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - app-tier

  db:
    image: mysql:5.7
    container_name: bookdb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-tier
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  book:
    build: .
    container_name: book
    links:
      - db
      - redis
    networks:
      - app-tier
    ports:
      - "5000:5000"
    environment:
      ENV: PROD
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: book
      APP_PORT: 5000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TTL: 300

networks:
  app-tier:
    driver: bridge
