version: "2"
services:
  app:
    build: .
    container_name: book
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      ENV: PROD
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: book
      APP_PORT: 5000

  db:
    image: mysql:5.7
    container_name: bookdb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
