CREATE DATABASE book;
USE book;

CREATE TABLE TB_REVIEW (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  book_id INT NOT NULL,
  rating FLOAT NOT NULL,
  review VARCHAR(250) NOT NULL,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);